name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  book_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - run: opam install . --deps-only --with-test --with-doc
      
      - run: ./book_test --chapter 8 --stage parse
      
