name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  book_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install dependencies
        run: opam install . --deps-only
      
      - name: Run book test
        run: ./ci.sh
      
